// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateSessionByPhone(ctx context.Context, arg CreateSessionByPhoneParams) (Session, error)
	CreateUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error)
}

var _ Querier = (*Queries)(nil)
