// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClearTestUsers(ctx context.Context) error
	CountUsers(ctx context.Context) (int64, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateUserByPhone(ctx context.Context, arg CreateUserByPhoneParams) (User, error)
	GetOrderById(ctx context.Context, id uuid.UUID) (GetOrderByIdRow, error)
	GetOrdersBelongingToStore(ctx context.Context, storeID uuid.UUID) ([]GetOrdersBelongingToStoreRow, error)
	GetPaymentsBelongingToStore(ctx context.Context, storeID uuid.UUID) ([]GetPaymentsBelongingToStoreRow, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductsBelongingToStore(ctx context.Context, storeID uuid.UUID) ([]GetProductsBelongingToStoreRow, error)
	GetStoreByID(ctx context.Context, id uuid.UUID) (GetStoreByIDRow, error)
	GetStoresBelongingToUser(ctx context.Context, userID uuid.UUID) ([]GetStoresBelongingToUserRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error)
}

var _ Querier = (*Queries)(nil)
