// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: store.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (
  name, thumbnail, user_id
) VALUES (
  $1, $2, $3
) RETURNING id, name, thumbnail, user_id, created_at, updated_at, deleted_at
`

type CreateStoreParams struct {
	Name      string    `json:"name"`
	Thumbnail string    `json:"thumbnail"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRowContext(ctx, createStore, arg.Name, arg.Thumbnail, arg.UserID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Thumbnail,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStoresBelongingToUser = `-- name: GetStoresBelongingToUser :one
SELECT name, thumbnail FROM stores
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetStoresBelongingToUserRow struct {
	Name      string `json:"name"`
	Thumbnail string `json:"thumbnail"`
}

func (q *Queries) GetStoresBelongingToUser(ctx context.Context, userID uuid.UUID) (GetStoresBelongingToUserRow, error) {
	row := q.db.QueryRowContext(ctx, getStoresBelongingToUser, userID)
	var i GetStoresBelongingToUserRow
	err := row.Scan(&i.Name, &i.Thumbnail)
	return i, err
}
