# fly.toml app configuration file generated for giggy-api on 2024-06-03T11:39:46+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'giggy-api'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
